# fly.toml app configuration file generated for howis on 2023-07-17T12:36:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jsk-chepset"
primary_region = "lax"

[env]
  ENV = "production"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
